-- Bagged discovery engine: boosted placement, weekly trends and personalized recommendations.
alter table public.products
  add column if not exists boosted_until timestamptz,
  add column if not exists boost_priority integer not null default 0;

create index if not exists products_boost_idx
  on public.products(boosted_until desc, boost_priority desc, created_at desc);

create table if not exists public.marketplace_events (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in ('search','view','save','cart_add','purchase')),
  product_id uuid references public.products(id) on delete set null,
  category_id uuid references public.categories(id) on delete set null,
  search_term text,
  created_at timestamptz not null default now()
);

create index if not exists marketplace_events_created_idx
  on public.marketplace_events(created_at desc);

create index if not exists marketplace_events_trend_idx
  on public.marketplace_events(event_type, created_at desc);

create index if not exists marketplace_events_user_idx
  on public.marketplace_events(user_id, created_at desc);

alter table public.marketplace_events enable row level security;

drop policy if exists "Marketplace analytics can be recorded" on public.marketplace_events;
create policy "Marketplace analytics can be recorded"
  on public.marketplace_events
  for insert
  to anon, authenticated
  with check (
    char_length(visitor_id) between 8 and 120
    and (
      user_id is null
      or user_id = (select auth.uid())
    )
  );

create or replace function public.record_marketplace_event(
  p_visitor_id text,
  p_event_type text,
  p_product_id uuid default null,
  p_category_id uuid default null,
  p_search_term text default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_event_type not in ('search','view','save','cart_add','purchase') then
    return false;
  end if;

  if p_visitor_id is null or char_length(btrim(p_visitor_id)) < 8 then
    return false;
  end if;

  insert into public.marketplace_events(
    visitor_id, user_id, event_type, product_id, category_id, search_term
  )
  values (
    btrim(p_visitor_id),
    (select auth.uid()),
    p_event_type,
    p_product_id,
    p_category_id,
    left(nullif(btrim(p_search_term), ''), 160)
  );

  return true;
end;
$$;

revoke all on function public.record_marketplace_event(text,text,uuid,uuid,text) from public, anon, authenticated;
grant execute on function public.record_marketplace_event(text,text,uuid,uuid,text) to public, anon, authenticated;

drop function if exists public.get_marketplace_discovery(uuid);
drop function if exists public.get_marketplace_discovery(uuid,text);

create or replace function public.get_marketplace_discovery(
  p_user_id uuid default null,
  p_visitor_id text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  -- Never trust a client-supplied user ID; personalize only for the current session.
  p_user_id := (select auth.uid());

  with user_category_scores as (
    select
      p.category_id,
      sum(
        case e.event_type
          when 'purchase' then 8
          when 'cart_add' then 5
          when 'save' then 4
          when 'view' then 2
          else 0
        end
      )::numeric as score
    from public.marketplace_events e
    join public.products p on p.id = e.product_id
    where e.created_at >= now() - interval '30 days'
      and (
        (p_user_id is not null and e.user_id = p_user_id)
        or
        (p_user_id is null and p_visitor_id is not null and e.visitor_id = p_visitor_id)
      )
      and e.event_type in ('view','save','cart_add','purchase')
    group by p.category_id
  ),
  personalized as (
    select p.id,
      (
        coalesce(ucs.score,0)
        + case when p.boosted_until > now() then 3 else 0 end
        + greatest(
            0,
            14 - extract(epoch from (now() - p.created_at)) / 86400
          )::numeric
      ) as score
    from public.products p
    left join user_category_scores ucs on ucs.category_id = p.category_id
    where p.status = 'published'
      and p.is_active = true
      and p.is_sold = false
      and p.stock > 0
      and (
        ucs.category_id is not null
        or not exists (select 1 from user_category_scores)
      )
    order by score desc, p.created_at desc
    limit 12
  ),
  trending_terms as (
    select lower(trim(e.search_term)) as term, count(*)::int as score
    from public.marketplace_events e
    where e.created_at >= date_trunc('week', now())
      and e.event_type = 'search'
      and e.search_term is not null
      and length(trim(e.search_term)) >= 2
    group by lower(trim(e.search_term))
    order by score desc
    limit 8
  ),
  trending_categories as (
    select p.category_id, count(*)::int as score
    from public.marketplace_events e
    join public.products p on p.id = e.product_id
    where e.created_at >= date_trunc('week', now())
      and e.event_type in ('view','save','cart_add','purchase')
    group by p.category_id
    order by score desc
    limit 6
  ),
  trending_products as (
    select p.id,
      sum(
        case e.event_type
          when 'purchase' then 8
          when 'cart_add' then 5
          when 'save' then 4
          else 2
        end
      )::numeric as score
    from public.marketplace_events e
    join public.products p on p.id = e.product_id
    where e.created_at >= date_trunc('week', now())
      and e.event_type in ('view','save','cart_add','purchase')
      and p.status = 'published'
      and p.is_active = true
      and p.is_sold = false
      and p.stock > 0
    group by p.id
    order by score desc, p.created_at desc
    limit 12
  ),
  boosted as (
    select p.id
    from public.products p
    where p.status = 'published'
      and p.is_active = true
      and p.is_sold = false
      and p.stock > 0
      and p.boosted_until > now()
    order by p.boost_priority desc, p.boosted_until desc, p.created_at desc
    limit 12
  ),
  fresh as (
    select p.id
    from public.products p
    where p.status = 'published'
      and p.is_active = true
      and p.is_sold = false
      and p.stock > 0
    order by p.created_at desc
    limit 12
  )
  select jsonb_build_object(
    'trending_terms', coalesce((select jsonb_agg(t) from trending_terms t), '[]'::jsonb),
    'trending_categories', coalesce((select jsonb_agg(tc) from trending_categories tc), '[]'::jsonb),
    'trending_ids', coalesce((select jsonb_agg(tp.id) from trending_products tp), '[]'::jsonb),
    'personalized_ids', coalesce((select jsonb_agg(p.id) from personalized p), '[]'::jsonb),
    'boosted_ids', coalesce((select jsonb_agg(b.id) from boosted b), '[]'::jsonb),
    'fresh_ids', coalesce((select jsonb_agg(f.id) from fresh f), '[]'::jsonb)
  )
  into result;

  return coalesce(result, '{}'::jsonb);
end;
$$;

revoke all on function public.get_marketplace_discovery(uuid,text) from public, anon, authenticated;
grant execute on function public.get_marketplace_discovery(uuid,text) to public, anon, authenticated;
